language: ruby
rvm:
- 2.4.1
sudo: required
dist: precise
install: gem install jekyll -v 3.3.0 && gem install jekyll-redirect-from && gem install
  s3_website
script: jekyll build
after_success:
- test $TRAVIS_BRANCH = "master" && s3_website push --config-dir=_config/production/
- test $TRAVIS_BRANCH = "staging" && s3_website push --config-dir=_config/staging/
branches:
  only:
  - master
  - staging
notifications:
  slack:
    rooms:
      secure: R3bPF23qWbAfL+jx38fpap2qXJt0aq5XE6VzWEAVTUUWSqj882QBHxkds6nlBx3X3pFck7Hx5nObeD1zUhbtTYFlCN25dwDj2P7R2nsxJJ/AeC8u4/zJYR7puNoPxl5b4tUmjDU7CVcsnPBhMqZz3XJuV6bQa9OytOJj2sn7oJFraPSKjC/1PY1YSOqiUT3pdq0A0IHrIHEhSccBgpJXVKBX8tEH/Fksfc/skDz3svQqAOeHxq5LlP6coBuNTeK2fhSZfLSwFSb3/hsVoBF97j79p8RVcIR7nYygSg67BCl3TDd5L52T2eTOa210SmuhXi/HGhu5YZJt5cowu/UkVE8YVPYjAO2BctVUt/YKwHab5lY4zIQ9fRv1gPxxnFhwMsP+a9t3ocN85+PlsXzPeN43pAhPVVvGH7Dj1iR47XjuOLrfKC+KtwW+vUdzwvxO1xNUYp0YOKSymQa3e6z/DY5Ruuvm8woZlvQRWtw+UmXsM/GhsWkYH6ZHFOaA90rRu9xKpMLhN8mucc4P0oEgE5jTnYH62IzEBpkuGDmOqkZVfBsftmju7sFrip6HCDO9SduQFvhvUh9xaGO5CCbhhvyJQlC2a2ahaXbdxpWa2zVW02q4Yd8ae54enqjfr15gTIH/W/K0X39ZqsAc/KPqTAdTs9fD/1vJ2ohpRP4/k10=
